---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynanextjs-v3
  labels:
    app: lynanextjs-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynanextjs-v3
  template:
    metadata:
      labels:
        app: lynanextjs-v3
    spec:
      containers:
        - name: lynanextjs-v3
          image: docker.io/phengbunath/lynanextjs-v3:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
